# Generated by Django 2.0.1 on 2018-03-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180310_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_accomodation', models.CharField(max_length=200)),
                ('type_of_room', models.CharField(max_length=200)),
                ('house_rent', models.IntegerField()),
                ('availability', models.CharField(choices=[('A', 'Available'), ('NA', 'Not_Available')], default='A', max_length=2)),
                ('location', models.CharField(max_length=200)),
                ('nearest_institution', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='profile_image')),
            ],
        ),
    ]
