# Generated by Django 2.0.1 on 2018-03-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_houses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
