# Generated by Django 2.0.1 on 2018-03-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
