# Generated by Django 2.0.1 on 2018-06-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20180516_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.AddField(
            model_name='profile',
            name='City_of_residence',
            field=models.CharField(default='lokoja', max_length=200),
            preserve_default=False,
        ),
    ]
