# Generated by Django 2.0.1 on 2018-06-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20180608_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Type_of_user',
            field=models.CharField(choices=[('S', 'Student'), ('E', 'Employed'), ('N', 'Not employed'), ('U', 'Undergraduate'), ('O', 'Others')], default='S', max_length=40),
        ),
    ]
