# Generated by Django 2.0.1 on 2018-07-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='name',
            field=models.TextField(default='sss'),
            preserve_default=False,
        ),
    ]
