# Generated by Django 2.0.1 on 2018-06-18 12:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Myhouses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name_of_accomodation', models.CharField(max_length=20)),
                ('type_of_apartment', models.CharField(choices=[('Flat', 'Flat'), ('Self Contain', 'Self_contained'), ('Bungalow', 'Bungalow'), ('Mini Flat', 'Mini_flat'), ('Duplex', 'Duplex')], max_length=20)),
                ('Number_of_rooms', models.IntegerField()),
                ('house_rent', models.IntegerField()),
                ('availability', models.CharField(choices=[('A', 'Available'), ('NA', 'Not_Available')], default='A', max_length=2)),
                ('location', models.CharField(max_length=200)),
                ('nearest_institution', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('house_image', models.ImageField(upload_to='documents/')),
                ('house_image2', models.ImageField(upload_to='documents/')),
                ('house_image3', models.ImageField(upload_to='documents/')),
                ('house_image4', models.ImageField(upload_to='documents/')),
                ('house_image5', models.ImageField(upload_to='documents/')),
                ('house_image6', models.ImageField(upload_to='documents/')),
                ('house_image7', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('house_image8', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('house_image9', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('house_image10', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('house_image11', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('house_image12', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
