# Generated by Django 2.0.1 on 2018-06-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_auto_20180622_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myhouses',
            old_name='location',
            new_name='City_or_town',
        ),
        migrations.AddField(
            model_name='myhouses',
            name='State',
            field=models.CharField(default='kogi', max_length=200),
            preserve_default=False,
        ),
    ]
