# Generated by Django 2.0.1 on 2018-06-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_auto_20180622_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhouses',
            name='State',
            field=models.CharField(choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa')], max_length=20),
        ),
    ]
