# Generated by Django 2.0.1 on 2018-07-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_auto_20180626_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhouses',
            name='Available_from',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myhouses',
            name='Fenced',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myhouses',
            name='Parking_space',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myhouses',
            name='Running_water',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myhouses',
            name='Size_of_room',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myhouses',
            name='Street',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myhouses',
            name='Toilet',
            field=models.CharField(choices=[('Private', 'private'), ('Shared', 'Shared')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
