# Generated by Django 2.0.1 on 2018-07-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_auto_20180711_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhouses',
            name='Landlord_number',
            field=models.CharField(max_length=200),
        ),
    ]
