# Generated by Django 2.0.1 on 2018-07-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0010_auto_20180711_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhouses',
            name='house_image',
            field=models.ImageField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image10',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image11',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image12',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image2',
            field=models.ImageField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image3',
            field=models.ImageField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image4',
            field=models.ImageField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image5',
            field=models.ImageField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image6',
            field=models.ImageField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image7',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image8',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image9',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='type_of_apartment',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Self Contain', 'Self contained'), ('Bungalow', 'Bungalow'), ('Mini Flat', 'Mini flat'), ('Student Lodge', 'Student lodge'), ('Student Hostel', 'Student hostel'), ('Looking for roommate', 'Looking for roommate')], max_length=20),
        ),
    ]
