# Generated by Django 2.0.1 on 2018-07-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0011_auto_20180711_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhouses',
            name='house_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image10',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image11',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image12',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image3',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image4',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image5',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image6',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image7',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image8',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image9',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
