# Generated by Django 2.0.1 on 2018-07-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0014_vip'),
    ]

    operations = [
        migrations.CreateModel(
            name='paid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('name_of_accomodation', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
