# Generated by Django 2.0.1 on 2018-07-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0016_paids'),
    ]

    operations = [
        migrations.AddField(
            model_name='paids',
            name='username',
            field=models.CharField(default='sweet', max_length=20),
            preserve_default=False,
        ),
    ]
