# Generated by Django 2.0.1 on 2018-07-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0017_paids_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='paids',
            name='name_of_accomodation',
            field=models.CharField(default='shshj', max_length=20),
            preserve_default=False,
        ),
    ]
