# Generated by Django 2.0.1 on 2018-07-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0018_paids_name_of_accomodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paids',
            name='name_of_accomodation',
            field=models.CharField(max_length=200),
        ),
    ]
