# Generated by Django 2.0.1 on 2018-07-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0019_auto_20180724_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paid',
            name='email',
        ),
    ]
