# Generated by Django 2.0.1 on 2018-07-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0020_remove_paid_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid',
            name='name_of_accomodation',
            field=models.CharField(max_length=200),
        ),
    ]
