# Generated by Django 2.0.1 on 2018-07-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0023_auto_20180724_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paids',
            name='myRef',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paids',
            name='username',
            field=models.TextField(max_length=20),
        ),
    ]
