# Generated by Django 2.0.1 on 2018-07-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0024_auto_20180725_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paids',
            name='accomodation',
        ),
        migrations.AlterField(
            model_name='paids',
            name='myRef',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paids',
            name='username',
            field=models.TextField(),
        ),
    ]
