# Generated by Django 2.0.1 on 2018-07-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0025_auto_20180725_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhouses',
            name='Payment_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
