# Generated by Django 2.0.1 on 2018-07-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0027_auto_20180725_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhouses',
            name='Payment_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
