# Generated by Django 2.0.1 on 2018-09-16 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0031_auto_20180914_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorVip', to=settings.AUTH_USER_MODEL),
        ),
    ]
