# Generated by Django 2.0.1 on 2018-09-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0032_vip_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhouses',
            name='type_of_apartment',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Self Contain', 'Self contained'), ('Bungalow', 'Bungalow'), ('Mini Flat', 'Mini flat'), ('Student Lodge', 'Student lodge'), ('Student Hostel', 'Student hostel'), ('Others', 'Others'), ('Looking for roommate', 'Looking for roommate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vip',
            name='type_of_apartment',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Self Contain', 'Self contained'), ('Bungalow', 'Bungalow'), ('Mini Flat', 'Mini flat'), ('Student Lodge', 'Student lodge'), ('Student Hostel', 'Student hostel'), ('Others', 'Others'), ('Looking for roommate', 'Looking for roommate')], max_length=20),
        ),
    ]
