# Generated by Django 2.0.1 on 2018-09-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0033_auto_20180916_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhouses',
            name='availability',
            field=models.CharField(choices=[('A', 'Available'), ('NA', 'Not_Available'), ('R', 'Reserved')], default='A', max_length=2),
        ),
    ]
